# Generated by Django 2.2 on 2021-04-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('staff_count', models.IntegerField()),
            ],
            options={
                'db_table': 'colg',
            },
        ),
    ]
