# Generated by Django 4.0.1 on 2022-03-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0002_collage'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.IntegerField(default=0),
        ),
    ]
