# Generated by Django 4.0.1 on 2022-03-16 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0005_alter_student_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='created_by',
        ),
    ]
